package vn.nextpay.nextpayrisk.rule;

import vn.nextpay.nrmrisk.dao.entity.VimoCalc24h;
import vn.nextpay.nrmrisk.dao.entity.VimoCalc;
import vn.nextpay.nrmrisk.dao.entity.VimoRiskTrans;

import java.time.LocalDateTime;

rule "intime approve cash-out offline draw time grater or equal to 3 time" salience 10
ruleflow-group "WITHDRAW"
lock-on-active
   when
     vimoRiskTrans: VimoRiskTrans(droolMethod=="CASH_OUT_OFFL" && droolsCustomerStatus=="APPROVE" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21);
     VimoCalc24h(countTrans24h >= 3);
   then
      vimoRiskTrans.addToList("VM-WITHDRAW-OFF-11001: Rút liên tiếp các giao dịch kể từ lần thứ 3 trong vòng 24h",1);
end

rule "intime approve cash-out offline amount greater than 10M fist time in 3 month"
ruleflow-group "WITHDRAW"
lock-on-active
   when
     vimoRiskTrans: VimoRiskTrans(droolMethod=="CASH_OUT_OFFL" && droolsCustomerStatus=="APPROVE" && transLocalDateTime.getHour() >=8 
     && transLocalDateTime.getHour() <=21 && amount > 3000000 && lastTransLocalDateTime.isBefore(transLocalDateTime.minus(3, ChronoUnit.MONTHS)));
   then
      vimoRiskTrans.addToList("VM-WITHDRAW-OFF-11002: Giao dịch lớn hơn 3M phát sinh lần đầu tiên trong vòng 3 tháng",2);
end


rule "intime approve cash-out online draw time grater or equal to 3 time" salience 10
ruleflow-group "WITHDRAW"
lock-on-active
   when
     vimoRiskTrans: VimoRiskTrans(droolMethod=="CASH_OUT_ONL" && droolsCustomerStatus=="APPROVE" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21);
     VimoCalc24h(countTrans24h >= 3);
   then
      vimoRiskTrans.addToList("VM-WITHDRAW-ON-11001: Rút liên tiếp các giao dịch kể từ lần thứ 3 trong vòng 24h",1);
end

rule "intime approve cash-out online amount greater than 3M fist time in 3 month"
ruleflow-group "WITHDRAW"
lock-on-active
   when
     vimoRiskTrans: VimoRiskTrans(droolMethod=="CASH_OUT_ONL" && droolsCustomerStatus=="APPROVE" && transLocalDateTime.getHour() >=8 
     && transLocalDateTime.getHour() <=21 && amount > 3000000 && lastTransLocalDateTime.isBefore(transLocalDateTime.minus(3, ChronoUnit.MONTHS)));
   then
      vimoRiskTrans.addToList("VM-WITHDRAW-ON-11002: Giao dịch lớn hơn 3M phát sinh lần đầu tiên trong vòng 3 tháng",2);
end


