package vn.nextpay.nextpayrisk.rule;


import vn.nextpay.nrmrisk.dao.entity.VimoCalc24h;
import vn.nextpay.nrmrisk.dao.entity.VimoCalc;
import vn.nextpay.nrmrisk.dao.entity.VimoRiskTrans;

import java.time.LocalDateTime;

import java.time.temporal.ChronoUnit;



rule "Sum Money GT 5M in 24H by approve onl IPT"
salience 10
ruleflow-group "DEPOSIT"
lock-on-active
   when
     vimoRiskTrans: VimoRiskTrans(droolMethod=="DEPOSIT_ONL" && droolsCustomerStatus=="APPROVE" && ( transLocalDateTime.getHour() >=22 || transLocalDateTime.getHour() <=7 ))
     vimoCalc24h : VimoCalc24h(amount24h>5000000 )
   then
      vimoRiskTrans.addToList("VM-DEPOSIT-ON-21001: Tổng số tiền các giao dịch lớn hơn 5M trong vòng 24h",1);
end

rule "Recharge seq from 3rd in 24h by approve onl"
ruleflow-group "DEPOSIT"
lock-on-active
    when
    vimoRiskTrans: VimoRiskTrans(droolMethod=="DEPOSIT_ONL"  && droolsCustomerStatus=="APPROVE" && ( transLocalDateTime.getHour() >=22 || transLocalDateTime.getHour() <=7 ))
      vimoCalc24h : VimoCalc24h(countTrans24h >= 3)
    then
        vimoRiskTrans.addToList("VM-DEPOSIT-ON-21002: Nạp liên tiếp các giao dịch kể từ lần thứ 3 trong vòng 24h",2);
end

rule "Recharge GT 3M in 3m by approve onl"
ruleflow-group "DEPOSIT"
lock-on-active
    when
    vimoRiskTrans: VimoRiskTrans(droolMethod=="DEPOSIT_ONL" && amount > 3000000  && droolsCustomerStatus=="APPROVE" 
    && ( transLocalDateTime.getHour() >=22 || transLocalDateTime.getHour() <=7 ) && lastTransLocalDateTime.isBefore(transLocalDateTime.minus(3, ChronoUnit.MONTHS)))
    then
        vimoRiskTrans.addToList("VM-DEPOSIT-ON-21003: Giá Trị giao dịch lớn hơn 3M phát sinh lần đầu tiên trong vòng 3 tháng",2);
end


rule "Sum Money GT 3M in 24H by not-approve onl IPT"
salience 10
ruleflow-group "DEPOSIT"
lock-on-active
   when
     vimoRiskTrans: VimoRiskTrans(droolMethod=="DEPOSIT_ONL" && droolsCustomerStatus=="NOT_APPROVE" && ( transLocalDateTime.getHour() >=22 || transLocalDateTime.getHour() <=7 ))
     vimoCalc24h : VimoCalc24h(amount24h>3000000 )
   then
      vimoRiskTrans.addToList("VM-DEPOSIT-ON-22001: Tổng số tiền các giao dịch lớn hơn 3M trong vòng 24h",1);
end



rule "Recharge seq from 2nd in 24h by not-approve onl"
ruleflow-group "DEPOSIT"
lock-on-active
    when
    vimoRiskTrans: VimoRiskTrans(droolMethod=="DEPOSIT_ONL"  && droolsCustomerStatus=="NOT_APPROVE" && ( transLocalDateTime.getHour() >=22 || transLocalDateTime.getHour() <=7 ))
      vimoCalc24h : VimoCalc24h(countTrans24h >= 2)
    then
        vimoRiskTrans.addToList("VM-DEPOSIT-ON-22002: Nạp liên tiếp các giao dịch kể từ lần thứ 2 trong vòng 24h",2);
end

rule "Recharge GT 500 in 3m by not-approve onl"
ruleflow-group "DEPOSIT"
lock-on-active
    when
    vimoRiskTrans: VimoRiskTrans(droolMethod=="DEPOSIT_ONL" && amount > 500000  && droolsCustomerStatus=="NOT_APPROVE" 
    && ( transLocalDateTime.getHour() >=22 || transLocalDateTime.getHour() <=7 ) && lastTransLocalDateTime.isBefore(transLocalDateTime.minus(3, ChronoUnit.MONTHS)))

    then
        vimoRiskTrans.addToList("VM-DEPOSIT-ON-22003: Giá Trị giao dịch lớn hơn 500 phát sinh lần đầu tiên trong vòng 3 tháng",2);
end


