package vn.nextpay.nextpayrisk.rule;

import vn.nextpay.nrmrisk.dao.entity.VimoCalc24h;
import vn.nextpay.nrmrisk.dao.entity.VimoCalc;
import vn.nextpay.nrmrisk.dao.entity.VimoRiskTrans;

import java.time.LocalDateTime;


//in time +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

rule "intime approve transfer out-wallet amount beyond 10M"
salience 10
ruleflow-group "TRANSFER"
lock-on-active
    when
         trans :VimoRiskTrans(droolMethod == "OUT_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "APPROVE" && amount > 10000000);
    then
        trans.addToList("VM-TRANSFER-OUT-11001: Số tiền giao dịch không được vượt quá 10M.",1);
    end

rule "intime approve transfer out-wallet tranfer 3 time in 24h"
ruleflow-group "TRANSFER"
lock-on-active
    when
        VimoCalc24h(countTrans24h >= 3);
         trans :VimoRiskTrans(droolMethod == "OUT_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "APPROVE");
    then
        trans.addToList("VM-TRANSFER-OUT-11002: Số lần giao dịch liên tiếp kể từ lần thứ 3 tròng vòng 24h.",2);
    end




rule "intime approve transfer in-wallet amount beyond 10M"
salience 10
ruleflow-group "TRANSFER"
lock-on-active
    when
         trans :VimoRiskTrans(droolMethod == "IN_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "APPROVE" && amount > 10000000);
    then
        trans.addToList("VM-TRANSFER-IN-11001: Số tiền giao dịch không được vượt quá 10M.",1);
    end


rule "intime approve transfer in-wallet tranfer 3 time in 24h"
ruleflow-group "TRANSFER"
lock-on-active
    when
        VimoCalc24h(countTrans24h >= 3);
         trans :VimoRiskTrans(droolMethod == "IN_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "APPROVE");
    then
        trans.addToList("VM-TRANSFER-IN-11002: Số lần giao dịch liên tiếp kể từ lần thứ 3 tròng vòng 24h.",2);
    end
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


rule "intime not approve transfer out-wallet amount beyond 1M"
salience 10
ruleflow-group "TRANSFER"
lock-on-active
    when
         trans :VimoRiskTrans(droolMethod == "OUT_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "NOT_APPROVE" && amount > 1000000);
    then
        trans.addToList("VM-TRANSFER-OUT-12001: Số tiền giao dịch không được vượt quá 1M.",1);
    end

rule "intime not approve transfer out-wallet tranfer 2 time in 24h"
ruleflow-group "TRANSFER"
lock-on-active
    when
        VimoCalc24h(countTrans24h >= 2);
         trans :VimoRiskTrans(droolMethod == "OUT_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "NOT_APPROVE");
    then
        trans.addToList("VM-TRANSFER-OUT-12002: Số lần giao dịch liên tiếp kể từ lần thứ 2 tròng vòng 24h.",2);
    end




rule "intime not approve transfer in-wallet amount beyond 1M"
salience 10
ruleflow-group "TRANSFER"
lock-on-active
    when
         trans :VimoRiskTrans(droolMethod == "IN_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "NOT_APPROVE" && amount > 1000000);
    then
        trans.addToList("VM-TRANSFER-IN-12001: Số tiền giao dịch không được vượt quá 1M.",1);
    end


rule "intime not approve transfer in-wallet tranfer 2 time in 24h"
ruleflow-group "TRANSFER"
lock-on-active
    when
        VimoCalc24h(countTrans24h >= 2);
         trans :VimoRiskTrans(droolMethod == "IN_WALLET" && transLocalDateTime.getHour() >=8 && transLocalDateTime.getHour() <=21 && droolsCustomerStatus == "NOT_APPROVE");
    then
        trans.addToList("VM-TRANSFER-IN-12002: Số lần giao dịch liên tiếp kể từ lần thứ 2 tròng vòng 24h.",2);
    end
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


