package vn.nextpay.nrmrisk.dao.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class versionCheck implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String version;

	public versionCheck() {
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public versionCheck(java.lang.String version) {
		this.version = version;
	}

}