package vn.nextpay.nrmrisk.dao.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VimoCalc24h implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double amount24h;
	private int countTrans24h;

	public VimoCalc24h() {
	}

	public java.lang.Double getAmount24h() {
		return this.amount24h;
	}

	public void setAmount24h(java.lang.Double amount24h) {
		this.amount24h = amount24h;
	}

	public int getCountTrans24h() {
		return this.countTrans24h;
	}

	public void setCountTrans24h(int countTrans24h) {
		this.countTrans24h = countTrans24h;
	}

	public VimoCalc24h(java.lang.Double amount24h, int countTrans24h) {
		this.amount24h = amount24h;
		this.countTrans24h = countTrans24h;
	}

}