package vn.nextpay.nrmrisk.dao.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VimoRiskTrans implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String id;
	private java.lang.Double amount;
	private java.lang.String droolMethod;
	private long customerId;
	private java.util.List<java.lang.String> rulesDescription;

	private java.lang.String droolsCustomerStatus;

	private java.time.LocalDateTime transLocalDateTime;

	private java.time.LocalDateTime lastTransLocalDateTime;

	private int importantRuleCounter;

	private int normalRuleCounter;

	public VimoRiskTrans() {
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.String getDroolMethod() {
		return this.droolMethod;
	}

	public void setDroolMethod(java.lang.String droolMethod) {
		this.droolMethod = droolMethod;
	}

	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public java.util.List<java.lang.String> getRulesDescription() {
		return this.rulesDescription;
	}

	public void setRulesDescription(
			java.util.List<java.lang.String> rulesDescription) {
		this.rulesDescription = rulesDescription;
	}

	public java.lang.String getDroolsCustomerStatus() {
		return this.droolsCustomerStatus;
	}

	public void setDroolsCustomerStatus(java.lang.String droolsCustomerStatus) {
		this.droolsCustomerStatus = droolsCustomerStatus;
	}

	public void addToList(String message,int ruleLevel) {
		rulesDescription.add(message);
		if(ruleLevel == 1) importantRuleCounter++;
		else normalRuleCounter++;
	}

	public java.time.LocalDateTime getTransLocalDateTime() {
		return this.transLocalDateTime;
	}

	public void setTransLocalDateTime(java.time.LocalDateTime transLocalDateTime) {
		this.transLocalDateTime = transLocalDateTime;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.time.LocalDateTime getLastTransLocalDateTime() {
		return this.lastTransLocalDateTime;
	}

	public void setLastTransLocalDateTime(
			java.time.LocalDateTime lastTransLocalDateTime) {
		this.lastTransLocalDateTime = lastTransLocalDateTime;
	}

	public int getImportantRuleCounter() {
		return this.importantRuleCounter;
	}

	public void setImportantRuleCounter(int importantRuleCounter) {
		this.importantRuleCounter = importantRuleCounter;
	}

	public int getNormalRuleCounter() {
		return this.normalRuleCounter;
	}

	public void setNormalRuleCounter(int normalRuleCounter) {
		this.normalRuleCounter = normalRuleCounter;
	}

	public VimoRiskTrans(java.lang.String id, java.lang.Double amount,
			java.lang.String droolMethod, long customerId,
			java.util.List<java.lang.String> rulesDescription,
			java.lang.String droolsCustomerStatus,
			java.time.LocalDateTime transLocalDateTime,
			java.time.LocalDateTime lastTransLocalDateTime,
			int importantRuleCounter, int normalRuleCounter) {
		this.id = id;
		this.amount = amount;
		this.droolMethod = droolMethod;
		this.customerId = customerId;
		this.rulesDescription = rulesDescription;
		this.droolsCustomerStatus = droolsCustomerStatus;
		this.transLocalDateTime = transLocalDateTime;
		this.lastTransLocalDateTime = lastTransLocalDateTime;
		this.importantRuleCounter = importantRuleCounter;
		this.normalRuleCounter = normalRuleCounter;
	}
}