package vn.nextpay.nrmrisk.dao.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VimoCalc implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Long customerId;
	private java.lang.String method;
	private java.lang.String statusTransaction;
	private java.time.LocalDateTime lastTransLocalDateTime;

	public VimoCalc() {
	}

	public java.lang.Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.Long customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getMethod() {
		return this.method;
	}

	public void setMethod(java.lang.String method) {
		this.method = method;
	}

	public java.lang.String getStatusTransaction() {
		return this.statusTransaction;
	}

	public void setStatusTransaction(java.lang.String statusTransaction) {
		this.statusTransaction = statusTransaction;
	}

	public java.time.LocalDateTime getLastTransLocalDateTime() {
		return this.lastTransLocalDateTime;
	}

	public void setLastTransLocalDateTime(
			java.time.LocalDateTime lastTransLocalDateTime) {
		this.lastTransLocalDateTime = lastTransLocalDateTime;
	}

	public VimoCalc(java.lang.Long customerId, java.lang.String method,
			java.lang.String statusTransaction,
			java.time.LocalDateTime lastTransLocalDateTime) {
		this.customerId = customerId;
		this.method = method;
		this.statusTransaction = statusTransaction;
		this.lastTransLocalDateTime = lastTransLocalDateTime;
	}

}